/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Sathish' at '12/29/16 12:43 PM' with Gradle 2.14.1
 *
 * @author Sathish, @date 12/29/16 12:43 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
